#!/usr/bin/env python3
"""
Phase 4: Daily Digest Generator
Generate daily summary in MD and Telegram brief format
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path

# Config
CACHE_DIR = os.path.join(os.path.dirname(__file__), '..', 'cache')
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'output')
OUTPUT_DIR = os.path.join(OUTPUT_DIR, 'daily')


def load_scored_items() -> list:
    """Load scored items"""
    scored_file = os.path.join(CACHE_DIR, 'scored_items.json')
    if os.path.exists(scored_file):
        with open(scored_file) as f:
            return json.load(f)
    return []


def format_telegram_brief(items: list) -> str:
    """Format items for Telegram brief"""
    lines = []
    lines.append("📊 **News Intelligence — Daily Brief**")
    lines.append(f"📅 {datetime.now().strftime('%Y-%m-%d %H:%M')} HKT")
    lines.append("")
    
    # Group by tier
    tier_order = ["🔥 Headline", "⭐ Important", "📌 Notable", "📝 General"]
    
    for tier in tier_order:
        tier_items = [i for i in items if i.get('tier') == tier]
        if not tier_items:
            continue
        
        tier_emoji = tier.split()[0]
        tier_name = tier.split()[1]
        
        lines.append(f"\n{tier_emoji} **{tier_name}** ({len(tier_items)})")
        lines.append("─" * 30)
        
        for item in tier_items[:5]:  # Top 5 per tier
            title = item.get('title', 'No Title')[:60]
            url = item.get('url', '')
            source = item.get('source', '')
            score = item.get('score', 0)
            
            lines.append(f"• {title}")
            if url:
                lines.append(f"  🔗 {url[:50]}...")
            lines.append(f"  📍 {source} | 🎯 {score}")
    
    return "\n".join(lines)


def format_markdown_digest(items: list) -> str:
    """Format items as Markdown document"""
    lines = []
    lines.append("# 📊 News Intelligence — Daily Digest")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} HKT")
    lines.append(f"**Total Items:** {len(items)}")
    lines.append("")
    
    # Summary stats
    tier_counts = {}
    for item in items:
        tier = item.get('tier', '📝 General')
        tier_counts[tier] = tier_counts.get(tier, 0) + 1
    
    lines.append("## 📈 Summary")
    lines.append("")
    lines.append("| Tier | Count |")
    lines.append("|------|-------|")
    for tier, count in sorted(tier_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {tier} | {count} |")
    lines.append("")
    
    # Detailed items by tier
    tier_order = ["🔥 Headline", "⭐ Important", "📌 Notable", "📝 General"]
    
    for tier in tier_order:
        tier_items = [i for i in items if i.get('tier') == tier]
        if not tier_items:
            continue
        
        tier_emoji, tier_name = tier.split()[0], tier.split()[1]
        lines.append(f"## {tier_emoji} {tier_name} ({len(tier_items)})")
        lines.append("")
        
        for i, item in enumerate(tier_items, 1):
            title = item.get('title', 'No Title')
            url = item.get('url', '')
            source = item.get('source', '')
            summary = item.get('summary', '')[:200]
            published = item.get('published', '')[:10]
            score = item.get('score', 0)
            
            lines.append(f"### {i}. {title}")
            lines.append("")
            lines.append(f"- **Source:** {source}")
            lines.append(f"- **Published:** {published}")
            lines.append(f"- **Score:** {score}/10")
            if url:
                lines.append(f"- **URL:** {url}")
            if summary:
                lines.append(f"- **Summary:** {summary}...")
            lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("*Generated by News Intelligence System*")
    
    return "\n".join(lines)


def save_digest(items: list):
    """Save digest to files"""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    date_str = datetime.now().strftime('%Y-%m-%d')
    
    # Save Markdown digest
    md_content = format_markdown_digest(items)
    md_file = os.path.join(OUTPUT_DIR, f'{date_str}.md')
    with open(md_file, 'w') as f:
        f.write(md_content)
    print(f"💾 Saved: {md_file}")
    
    # Save Telegram brief
    tg_content = format_telegram_brief(items)
    tg_file = os.path.join(os.path.dirname(__file__), '..', 'output', f'brief_{date_str}.txt')
    with open(tg_file, 'w') as f:
        f.write(tg_content)
    print(f"💾 Saved: {tg_file}")
    
    return md_file, tg_file


def main():
    print("=" * 50)
    print("Phase 4: Daily Digest Generator")
    print("=" * 50)
    
    items = load_scored_items()
    
    if not items:
        print("❌ No scored items found. Run scorer.py first.")
        return
    
    print(f"📥 Loaded {len(items)} scored items")
    
    # Show stats
    tier_counts = {}
    for item in items:
        tier = item.get('tier', '📝 General')
        tier_counts[tier] = tier_counts.get(tier, 0) + 1
    
    print("\n📊 Items by Tier:")
    for tier, count in sorted(tier_counts.items(), key=lambda x: -x[1]):
        print(f"  {tier}: {count}")
    
    # Generate and save
    md_file, tg_file = save_digest(items)
    
    print(f"\n✅ Digest generated:")
    print(f"  📄 Markdown: {md_file}")
    print(f"  📱 Telegram: {tg_file}")
    
    # Also print Telegram brief for quick view
    print("\n" + "=" * 50)
    print("📱 Telegram Brief Preview:")
    print("=" * 50)
    print(format_telegram_brief(items))
    
    return items


if __name__ == '__main__':
    main()